### PR TITLE
MS AD Graph: Feature - Added admin permissions and advanced queries

### PR DESCRIPTION
**Pull request by alnumac**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [x] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Added option to use admin granted permissions
- Added expand_string parameter to list users, list groups, list user attributes, get group and list group members
- Added use_advanced_query parameter to list users, list groups, list user attributes, get group and list group members

## What is the current behavior? (OPTIONAL)
- The app only supports delegated permissions, and not admin-granted app permissions
- The app does not use the expand parameter to explore object relationships
- Advanced query capabilities cannot be used for complex conditions.
- The app has a lot of compatibility code for Python 2, while not supporting it.

## What is the new behavior? (OPTIONAL)
- Implemented the same admin consent settings as the O365 Graph app
- Implemented the logic to use the new settings for token generation and rest calls
- Updated the test connectivity action to allow non-interactive tests when admin consent is already provided
- Implemented the expand_string parameter on relevant actions to allow flexible exploration of AD object relationships
- Implemented the use_advanced_query parameter on relevant actions to allow complex queries, and deeper exploration of object relationships
- Removed py2 checks and compatibility functions
- Made use of f strings to improve code readability
- Updated bare except statements as they could cause issues
- Fixed the inconsistent return signature of _make_rest_call_helper
- Fixed _make_rest_call_helper not actually retrying when a token is expired
- Updated _handle_pagination parameters to match other helper functions

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by aparekh-crest** [comment]
Hello @alnumac,
- list user attributes
- get group
- get group members
For above three actions, we have parameters `select string`, `expand string` and `use advance query`
`expand string` parameter is not supported with advance query as per the [docs](https://learn.microsoft.com/en-us/graph/query-parameters#expand-parameter)  and `select string` parameter is use to limit the properties for any object.
I haven’t seen any relation between `select string` and `use advance query` parameters, is it relevant to use advance query for above actions?
Can you please provide your inputs for above cases?

**Comment by aparekh-crest** [comment]
Hi @alnumac,

As per the given [docs](https://learn.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http#optional-query-parameters), we can use $levels parameter along with $expand parameter, but we don't have $levels parameter implemented for these actions, so right now we can remove advance query parameter for above three actions and further once $levels parameter will be added then we are okay to use advance query parameter or we should add $levels parameter for advance query in this PR.
Please provide your inputs.

**Comment by alnumac** [comment]
Hi @aparekh-crest,

The $levels is a sub-parameter of $expand for the manager value, and wouldn't make much sense as separate parameter. If you provide the following value to the expand field for list user attributes, with advanced query enabled, you receive the whole hierarchy above the employee.

`manager($levels=max;$select=id,displayName)`

I believe that removing the advanced query parameter will just restrict the app's current capabilities.

**Comment by aparekh-crest** [comment]
Hi @alnumac ,
We can use $levels as sub-parameter in $expand parameter as per the given example.
Thanks

**Comment by alnumac** [comment]
Hi @aparekh-crest,

I'm not sure on the meaning of your previous message. Do you agree to leave the advanced query capabilities checkbox in or not?

To me, leaving the checkbox in enables advanced users to use advanced MS Graph functionalities. Removing it just limits what the app can achieve. Adding sub-parameters will just be more complex, less future-proof and more confusing than the Advanced checkbox is.

**Comment by aparekh-crest** [comment]
Hi @alnumac ,
Yes, I am agree to leave checkbox in, instead of creating separate parameter, we can pass it as sub-parameter with advance query enabled.

**Comment by aparekh-crest** [comment]
Hello @alnumac ,
For `list group members` action, you have added `expand string` and `use advance query` parameters, can you please provide any valid inputs which we can pass into expand string?
I checked the docs for this API, I haven't find any case for this parameter, though it is also supported param for this API

**Comment by aparekh-crest** [comment]
Hi @alnumac ,
Can you please provide the cases for expand string parameter of `list group members` action, else we can remove this parameter from this action only as we don't have any valid inputs.

**Review by alexa-phantom — APPROVED** [review]

**Review by ricardo-phantom — APPROVED** [review]

**Pull request merged**
